{{- if and .Values.global.registry.credentials.username ( not .Values.global.registry.existingSecret ) -}}
# Credentials for private registry
kind: Secret
apiVersion: v1
metadata:
  name: {{ template  "fullname" . }}-registrypullsecret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
