apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" | quote }}
    app.kubernetes.io/component: id-store
    app.kubernetes.io/part-of: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      {{ if .Values.routerDSA.enabled }}
      targetPort: 11389
      {{- else }}
      targetPort: 10389
      {{- end }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort}}
      {{- end }}
      protocol: TCP
      name: ldap
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/component: id-store
    app.kubernetes.io/part-of: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
