{{- if and .Values.persistence.enabled (not .Values.persistence.existingPVCName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.persistence.keepAfterUninstall }}
    "helm.sh/resource-policy": keep
{{- end }}
spec:
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}