{{- if .Values.admin.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-siteminder-adminui-ssl-rewrite
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /iam/siteminder/console
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

spec:
  ingressClassName: {{ .Values.admin.ingress.className }}
  defaultBackend:
    resource:
    service:
      name: default-https-backend
      port: 
        number: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
      - path: /adminui
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-siteminder-admin
            port: 
              number: {{ .Values.admin.ingress.servicePort }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-siteminder-adminui-ovm-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-ovm-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.admin.ingress.className }}
  defaultBackend:
    resource:
    service:
      name: default-https-backend
      port: 
        number: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /sitemindermonitor
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Release.Name }}-siteminder-ovm-admin
              port: 
                number: {{ .Values.admin.ingress.servicePort }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-siteminder-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: {{ .Values.admin.ingress.className }}
  defaultBackend:
    service:
      name: default-https-backend
      port: 
        number: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /iam/
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-siteminder-admin
              port: 
                number: {{ .Values.admin.ingress.servicePort }}
        - path: /castylesr5.1.1/
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-siteminder-admin
              port: 
                number: {{ .Values.admin.ingress.servicePort }}
  tls:
  - hosts:
    - {{ .Values.admin.ingress.hostName }} 
    secretName: {{ .Release.Name }}-casso.ca.local-tls
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-siteminder-rest-endpoint
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: {{ .Values.admin.ingress.className }}
  defaultBackend:
    service:
      name: default-https-backend
      port: 
        number: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /ca/api/sso/services/
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-siteminder-admin
              port: 
                number: {{ .Values.admin.ingress.servicePort }}
{{- end }}
