{{- if .Values.admin.enabled -}}
---
## Administrative Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-admin
  namespace: {{ .Release.Namespace }} 
  annotations:
    description: "Service for the Admin Server"
  labels:
    app: {{ template "fullname" . }} 
    release: {{ .Release.Name }} 
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.global.policyServerParams.admin.service.type }}
  ports:
  - name: adminuihttp
    port: 8080
    targetPort: 8080
  - name: adminuihttps
    port: 8443
    targetPort: 8443
  - name: accountingport
    port: 44441
    targetPort: 44441
  - name: authenticationport
    port: 44442
    targetPort: 44442
  - name: authorizationport
    port: 44443
    targetPort: 44443
  {{- if eq (( .Values.global.debugmode | default "NO" | lower )) "yes" }}
  - name: adminps-gdbserver
    port: 4444
    targetPort: 4444
  - name: adminps-javadebug
    port: 9001 
    targetPort: 9001
  - name: adminui-java
    port: 8787
    targetPort: 8787 
  {{- end }}
  selector:
      app: {{ template "fullname" . }} 
      release: {{ .Release.Name }} 
      ca.com/sso-pod: admin
      ca.com/sso-role: admin
      app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
      app.kubernetes.io/component: administrative-server
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
---
{{- if .Values.global.policyServerParams.ovm.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-ovm-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "Service for the OVM Service"
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: administrative-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: ovmmonitorport
    port: 44449
    targetPort: 44449
  - name: httpsovm
    port: 8443
    targetPort: 8443
  selector:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}
      statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-siteminder-admin-0
      app.kubernetes.io/name: {{ .Release.Name }}-siteminder-admin
      app.kubernetes.io/component: administrative-server
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
