{{- if and (.Values.policyServer.enabled ) (eq (( .Values.global.policyServerParams.service.type )) "LoadBalancer") }}

## Policy Server Health probe Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-policy-server-probe
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "Service for the Policy Server Health Probe"
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-policy-server
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: policy-server
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  ports:
  - name: pshealthprobe
    port: {{ .Values.global.policyServerParams.healthProbe.port }}
    nodePort: {{ .Values.policyServer.serviceNodePort.psHealthProbe }}
    targetPort: {{ .Values.global.policyServerParams.healthProbe.port }}
  selector:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}
      ca.com/sso-pod: policy-server
      ca.com/sso-role: policyserver
      app.kubernetes.io/name: {{ .Release.Name }}-siteminder-policy-server
      app.kubernetes.io/component: policy-server
      app.kubernetes.io/part-of: {{ template "fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
