{{- if and (.Values.admin.enabled) (.Values.admin.ingress.tlsCrt) (.Values.admin.ingress.tlsKey) -}}
apiVersion: v1
data:
  tls.crt: {{ .Values.admin.ingress.tlsCrt }}
  tls.key: {{ .Values.admin.ingress.tlsKey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-casso.ca.local-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
