---
# Healthcheck configuration script for metricsexporter containers
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-agmetricsexporter-healthcheck
  namespace: {{ .Release.Namespace }} 
  labels:
    release: {{ .Release.Name }} 
    app: {{ template "fullname" . }} 
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-access-gateway
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: access-gateway
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  metricsExporter-health-check.sh: |-
    OK=$(netstat -tlnp | awk '/:9090 */ {split($NF,a,"/"); print a[2]}' | grep java)
    if [ "$OK" == "java" ]; then
        exit 0
    else
        exit 1
    fi
