# Access Gateway Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-access-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "Service for the Access Gateway"
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-siteminder-access-gateway
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: access-gateway
    app.kubernetes.io/part-of: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sso.accessGateway.service.type }}
  ports:
  - name: http
    port: 6080
    targetPort: 6080
  - name: https
    port: 6443
    targetPort: 6443
  {{- if eq (( .Values.global.debugmode | default "NO" | lower )) "yes" }}
  - name: ag-gdbserver
    port: 4444
    targetPort: 4444
  - name: ag-javadebug
    port: 9001 
    targetPort: 9001 
  {{- end }}
  selector: 
      app: {{ template "fullname" . }}
      ca.com/sso-pod: access-gateway
      app.kubernetes.io/name: {{ .Release.Name }}-siteminder-access-gateway
      app.kubernetes.io/component: access-gateway
      app.kubernetes.io/part-of: {{ template "fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
