apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJia3JoaW0xMDA0IiwicGFzc3dvcmQiOiJQQHNzd29yZDEyMyIsImVtYWlsIjoiYm9ua3l1bkBnbWFpbC5jb20iLCJhdXRoIjoiWW10eWFHbHRNVEF3TkRwUVFITnpkMjl5WkRFeU13PT0ifX19
kind: Secret
metadata:
  name: docker-hub-registrypullsecret
type: kubernetes.io/dockerconfigjson
