$PS_HOME/bin/smconfigtool.sh $TOOLOPERATION "SESSION_STORE" $SESSION_STORE_ODBC_TYPE $CREATEONLY_DSN $SESSION_STORE_PORT \
                "$SESSION_STORE_DSN" "$SESSION_STORE_USER" "$SESSION_STORE_USER_PASSWORD" "$SESSION_STORE_HOST" \
                "$SESSION_STORE_DATABASE_NAME" "$SESSION_DATABASE_SERVICE_NAME" "$CONNECTION_CHECK"