apiVersion: v1
kind: Pod
metadata:
  name: telnet-test-pod
  labels:
    purpose: demonstrate-telnet
spec:
  containers:
  - name: telnet-container
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    stdin: true
    tty: true
