apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-pod
spec:
  containers:
  - name: nfs-client-container
    image: gmoney23/nfs-client-provisioner
  imagePullSecrets:
  - name: docker-hub-registrypullsecret